# Generated by Django 4.0 on 2022-02-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listItems', '0006_alter_searchfield_is_duplicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchfield',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
